# Generated by Django 3.0.5 on 2020-04-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='doctor',
            field=models.ManyToManyField(related_name='specialties', to='users.Doctor'),
        ),
    ]
